apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server
  namespace: elastic-stack
spec:
  config:
    spec:
      containers:
      - name: apm-server
        resources:
         requests:
           cpu: 800m
           memory: 512mi
         limits:
           cpu: 1000m
           memory: 1Gi 
  count: 1
  elasticsearchRef:
    name: elasticsearch
  http:
    service:
      spec:
        type: ClusterIP 
  version: 8.10.2